version: '2'
services:
  app:
    image: nycdb-load-dataset:boop
    build: .
    volumes:
      - .:/app
    environment:
      DATABASE_URL: ${DATABASE_URL}
      USE_TEST_DATA: ${USE_TEST_DATA}
    links:
      - db
  db:
    image: postgres:9.6
    environment:
      - POSTGRES_USER=nycdb
      - POSTGRES_DB=nycdb
      - POSTGRES_PASSWORD=nycdb
