version: '3.4'
services:
  app:
    image: justfixnyc/nycdb-k8s-loader:dev
    build:
      context: .
      target: dev
    volumes:
      - .:/app
    environment:
      DATABASE_URL: ${DATABASE_URL}
      USE_TEST_DATA: ${USE_TEST_DATA}
      DATASET: ${DATASET}
      SLACK_WEBHOOK_URL: ${SLACK_WEBHOOK_URL}
      TEST_DATABASE_URL: ${TEST_DATABASE_URL}
      ROLLBAR_ACCESS_TOKEN: ${ROLLBAR_ACCESS_TOKEN}
    links:
      - db
  db:
    image: postgres:9.6
    environment:
      - POSTGRES_USER=nycdb
      - POSTGRES_DB=nycdb
      - POSTGRES_PASSWORD=nycdb
