apiVersion: batch/v1
kind: Job
metadata:
  name: load_dataset
spec:
  template:
    spec:
      containers:
      - name: load_dataset
        image: nycdb-load-dataset
      restartPolicy: Never
  backoffLimit: 4
