apiVersion: batch/v1
kind: CronJob
metadata:
  name: load-dataset
spec:
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: load-dataset
            resources:
              requests:
                memory: "128Mi"
                cpu: "1000m"
          restartPolicy: Never
      backoffLimit: 2
  timeZone: "America/New_York"
