apiVersion: batch/v1
kind: Job
metadata:
  name: load-dataset
spec:
  template:
    spec:
      containers:
      - name: load-dataset
        image: justfixnyc/nycdb-k8s-loader:dev
      restartPolicy: Never
  backoffLimit: 4
