apiVersion: batch/v1
kind: Job
metadata:
  name: load-dataset
spec:
  template:
    spec:
      containers:
      - name: load-dataset
        image: nycdb-load-dataset:boop
      restartPolicy: Never
  backoffLimit: 4
