apiVersion: batch/v1
kind: CronJob
metadata:
  name: load-dataset
spec:
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: load-dataset
          restartPolicy: OnFailure
      backoffLimit: 2
