apiVersion: batch/v1
kind: CronJob
metadata:
  name: load-dataset
spec:
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: load-dataset
            image: justfixnyc/nycdb-k8s-loader:dev
          restartPolicy: Never
      backoffLimit: 4
