apiVersion: batch/v1
kind: CronJob
metadata:
  name: load-dataset
spec:
  jobTemplate:
    spec:
      template:
        spec:
          volumes:
          - name: ssh-keys-v
            secret:
              secretName: ssh-keys
              defaultMode: 0600 
          containers:
          - name: load-dataset
            volumeMounts:
            - name: ssh-keys-v
              readOnly: true
              mountPath: "/root/.ssh"
          restartPolicy: Never
      backoffLimit: 0
